version: '3'
services:
  phoenix:
    image: node:lts
    volumes:
      - ../:/opt/app
      - /watorvapor/wai.storage/dumps.wikimedia.org/cnwiki:/watorvapor/wai.storage/dumps.wikimedia.org/cnwiki
      - /storage/master/wai.storage/phoenix/cnwiki:/storage/master/wai.storage/phoenix/cnwiki
    working_dir: "/opt/app/cli"
    command: node ./phoenix.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
