version: '3'
services:
  daemon:
    image: node:lts
    volumes:
      - ../:/opt/app
      - /storage/dhtfs/cluster:/storage/dhtfs/cluster
      - /tmp/dht_ermu_api_unix_dgram:/tmp/dht_ermu_api_unix_dgram
    working_dir: "/opt/app/cli"
    command: node ./daemon.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 256M
  redis_dht:
    image: node:lts
    volumes:
      - ../:/opt/app
      - /tmp/dht_ermu_api_unix_dgram:/tmp/dht_ermu_api_unix_dgram
    working_dir: "/opt/app/cli"
    command: node ./redis_dht.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
