version: '3'
services:
  indexer:
    image: node:lts
    volumes:
      - ../:/opt/app
      - /storage/dhtfs/cluster/news_pumper:/storage/dhtfs/cluster/news_pumper
      - /dev/shm:/dev/shm
    working_dir: "/opt/app/indexer"
    command: node ./app.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
