version: '3'
services:
  proxyWS:
    image: node:lts
    volumes:
      - ../:/opt/app
      - /dev/shm:/dev/shm
    working_dir: "/opt/app/cli"
    command: node ./wsproxy/ws.ermu.unix.js
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
