version: '3'
services:
  news_pumper_cn:
    image: node:lts
    volumes:
      - ./:/opt/app
      - /storage/dhtfs/cluster/news_pumper:/storage/dhtfs/cluster/news_pumper
    working_dir: "/opt/app/news_pumper"
    command: node ./appCN.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
