version: '3'
services:
  redis:
    image: redis:6
    volumes:
      - ./redis/redis.conf:/opt/redis/redis.conf
      - /dev/shm:/dev/shm
    command: redis-server /opt/redis/redis.conf
    environment:
      TZ: Asia/Tokyo
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    network_mode: "none"
