version: '3'
services:
  daemon:
    image: ipfs/go-ipfs:v0.4.23
    volumes:
      - /storage/dhtfs/cluster/ipfs-storage:/data/ipfs
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
